# Generated by Django 3.1.1 on 2020-10-01 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_message', models.DateField(default=django.utils.timezone.now)),
                ('content_message', models.TextField(default="he wanted to make a joke and he didn't write anything down. you're huge man !")),
            ],
        ),
    ]
