# Generated by Django 3.1.1 on 2020-10-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_giving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_giving', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='id_receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiving', to=settings.AUTH_USER_MODEL),
        ),
    ]
